workflows:
  android-build:
    name: Build Android App
    max_build_duration: 60
    environment:
      vars:
        BUILD_TYPE: "debug"
      java: 17
    scripts:
      - name: Build APK
        script: |
          cd "SmartD-plant(Android)"
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - SmartD-plant(Android)/app/build/outputs/**/*.apk
